// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr9JJE23w2ocMO620McgqerJoiyruiWXU',
    appId: '1:491274091057:web:77411cd246d71f5295f310',
    messagingSenderId: '491274091057',
    projectId: 'autheticator-eea35',
    authDomain: 'autheticator-eea35.firebaseapp.com',
    storageBucket: 'autheticator-eea35.appspot.com',
    measurementId: 'G-V105FRE64W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwYR1xczA2WVraRlYYZJibnNUKSAjOhfk',
    appId: '1:491274091057:android:bb8001e377e1f8bf95f310',
    messagingSenderId: '491274091057',
    projectId: 'autheticator-eea35',
    storageBucket: 'autheticator-eea35.appspot.com',
  );
}
